// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpBLH8HfVZFp-0kNCdd4B0CoCrjgFVgYw',
    appId: '1:626836631956:android:cec2670b1d61d150895f81',
    messagingSenderId: '626836631956',
    projectId: 'esp32firebase-1944e',
    databaseURL: 'https://esp32firebase-1944e-default-rtdb.firebaseio.com',
    storageBucket: 'esp32firebase-1944e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM5PWV39KRUpBCHTdSqZoJbJ-d1njuGzg',
    appId: '1:626836631956:ios:6ddabab95ab01e63895f81',
    messagingSenderId: '626836631956',
    projectId: 'esp32firebase-1944e',
    databaseURL: 'https://esp32firebase-1944e-default-rtdb.firebaseio.com',
    storageBucket: 'esp32firebase-1944e.appspot.com',
    iosClientId: '626836631956-4523h2onuipbg6ogb5h0qjbvo0pvlen8.apps.googleusercontent.com',
    iosBundleId: 'com.google.firebase.presents.boxapp',
  );
}
